name: "Build Release"

on:
  push:
    tags:
      - '*'
#      - '/^\d+\.\d+\.\d+(-\w+)?$/'

jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}