name: "Build Release"

on:
  push:
    tags:
      - '*'
#      - '/^\d+\.\d+\.\d+(-\w+)?$/'

jobs:
  release:
    name: "Release"

    runs-on: "ubuntu-latest"

    steps:
      - name: Create Package dist
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}