name: Generate SVG from DOT and commit

on:
  push:
    paths:
      - 'docs/diagramma-er.dot'

jobs:
  generate-svg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"              
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - name: Cache Graphviz installation
        id: cache-graphviz
        uses: actions/cache@v2
        with:
          path: /var/cache/apt/archives
          key: graphviz-${{ runner.os }}-${{ hashFiles('**/apt-get.lock') }}
          restore-keys: |
            graphviz-${{ runner.os }}-

      - name: Install Graphviz
        shell: bash
        run: |
          sudo apt update
          sudo apt -f install
          sudo apt install -y graphviz

      - name: Generate SVG from DOT
        run: dot -Tsvg docs/diagramma-er.dot -o diagramma-er-gv.svg

      - name: Commit and push changes
        run: |
          git add diagramma-er-gv.svg
          git commit -m "Generate SVG from DOT"
          git push origin
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
